### ISSUE TITLE
Add CSpell

### ISSUE THREAD

**Issue by ryicoh** [tsuyoshicho/vim-efm-langserver-settings#155]
Hi✋

I suggest to add [cspell](https://cspell.org) which is a standard spell checker in vscode.

```
tools:
  cspell: &cspell
    lint-command: 'cspell-cli lint --no-color'
    lint-formats:
      - '%f:%l:%c -%m'
languages:
  =:
    - <<: *cspell
```
