### ISSUE TITLE
feat: jq lint

### ISSUE THREAD

**Issue by tsuyoshicho** [tsuyoshicho/vim-efm-langserver-settings#60]
Thansk slack info

```yaml
 json-jq: &json-jq
    lint-command: 'jq'
    lint-stdin: true
    lint-offset: 1
    lint-formats:
      - '%m at line %l, column %c'
```
