### ISSUE TITLE
new command style

### ISSUE THREAD

**Issue by tsuyoshicho** [tsuyoshicho/vim-efm-langserver-settings#93]
for this style

```yaml
 markdown-textlint: &markdown-textlint
    lint-command: 'textlint -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m [%trror/%r]'
    root-markers:
      - .textlintrc
    commands:
      - command: 'textlint --fix ${INPUT}'
        title: 修正を適用
```
